### ISSUE TITLE
cname doesn't seem functional

### ISSUE THREAD

**Issue by willscott** [applied-mixnetworks/mixbib#13]
http://mixbib.censor.watch is going to github but just gives a 404

unclear if the 'use /docs' on master is working the way we want, or if we should make a rendered branch in the repo to point to.

**Comment by david415** [comment]
i think this is because there is no index.html in the docs dir?

**Comment by willscott** [comment]
I pushed a 'gh-pages' branch with an index.  Can you try pointing pages to that branch instead of the master /docs folder?

**Comment by david415** [comment]
yeah ok i just did that.
looks like it works at this url
https://applied-mixnetworks.github.io/mixbib/

**Comment by david415** [comment]
oh i see i had to reenter the DNS name in the github settings. ok it works now
