### ISSUE TITLE
Add: cMix: Anonymization by High-Performance Scalable Mixing

### ISSUE THREAD

**Issue by willscott** [applied-mixnetworks/mixbib#7]
https://eprint.iacr.org/2016/008.pdf

cMix is the first practical system that can prevent traffic analysis of
chat messages at scale. It creates a complete anonymity set every
second for all messages sent during the previous second.
cMix uniquely requires no public-key operations during the
sending of a chat message—neither by the smart phone sending
the message, the roughly ten nodes that process each message in
sequence, nor the receiving smart phone.

**Comment by burdges** [comment]
Attack paper : 

https://eprint.iacr.org/2016/729.pdf

Chaum et al. have very recently introduced cMix as the first
practical system that offers senders-receivers unlinkability at scale. cMix
is claimed by its authors to be secure unless all nodes collude (or less
than two senders are honest). We argue their assertion does not hold and
sustain our statement by three different types of attacks: tagging attack,
insider attack and passive attack. For each one, we discuss the settings
that make it feasible and possible countermeasures.
