### ISSUE TITLE
Add: Vuvuzela: Scalable Private Messaging Resistant to Traffic Analysis

### ISSUE THREAD

**Issue by willscott** [applied-mixnetworks/mixbib#8]
https://people.csail.mit.edu/nickolai/papers/vandenhooff-vuvuzela.pdf

Note: Even with verifiable mixnets, how you apply it makes a big difference. if the content is linkable, you need to resort to adding noise to mitigate that issue. Vuvuzela can be seen as an answer to that problem.

Abstract: Private messaging over the Internet has proven challenging to
implement, because even if message data is encrypted, it is
difficult to hide metadata about who is communicating in the
face of traffic analysis. Systems that offer strong privacy guar-
antees, such as Dissent [36], scale to only several thousand
clients, because they use techniques with superlinear cost in
the number of clients (e.g., each client broadcasts their mes-
sage to all other clients). On the other hand, scalable systems,
such as Tor, do not protect against traffic analysis, making
them ineffective in an era of pervasive network monitoring.

**Comment by burdges** [comment]
It's successor Alpenhorn makes unreasonable bandwidth assumptions:
https://vuvuzela.io/alpenhorn-extended.pdf
